### ISSUE TITLE
Incompatibildad de tipos de respuesta del endpoint hacia el Frontend

### ISSUE THREAD

**Issue by phreakphreak** [nsdonato/planetas_api#6]
### Backend estructura actual de la respuesta del endpoint:
![image](https://user-images.githubusercontent.com/91038818/189248130-8192b097-1172-4589-aaed-145730bc6c83.png)

![image](https://user-images.githubusercontent.com/91038818/189247671-69ed556e-5abb-4808-a249-3fd6dbf70d08.png)

### Frontend estructura con la que se espera en la respuesta:
![image](https://user-images.githubusercontent.com/91038818/189247903-6cb48111-47e8-45b4-9b31-15b43f1d7acd.png)

**Comment by PabMai** [comment]
Se realizo las modificaciones
